use_frameworks!

platform :ios, '8.0'

target 'GMPhoneInfo_Example' do
  pod 'GMPhoneInfo', :path => '../'

  target 'GMPhoneInfo_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
